

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.conv_result_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.max_result_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.min_result_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.avg_result_U"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_r_s_axi_U"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem_m_axi_U"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Block_entry_gmem_rd_proc_U0"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_gmem_rd_proc_U0.grp_convolution_1_1_fu_62"},
	{"ID" : "11", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_gmem_rd_proc_U0.grp_convolution_1_1_fu_62.mul_32s_31ns_63_1_1_U9"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_gmem_rd_proc_U0.grp_pooling_1_1_fu_76"},
	{"ID" : "13", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_gmem_rd_proc_U0.grp_pooling_1_1_fu_76.mul_20s_20s_20_1_1_U16"},
	{"ID" : "14", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_gmem_rd_proc_U0.grp_pooling_1_1_fu_76.mul_32s_30ns_62_1_1_U17"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_gmem_rd_proc_U0.grp_pooling_2_1_fu_87"},
	{"ID" : "16", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_gmem_rd_proc_U0.grp_pooling_2_1_fu_87.mul_20s_20s_20_1_1_U25"},
	{"ID" : "17", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_gmem_rd_proc_U0.grp_pooling_2_1_fu_87.mul_32s_30ns_62_1_1_U26"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_gmem_rd_proc_U0.grp_pooling_1_2_fu_98"},
	{"ID" : "19", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_gmem_rd_proc_U0.grp_pooling_1_2_fu_98.mul_20s_20s_20_1_1_U32"},
	{"ID" : "20", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.Block_entry_gmem_rd_proc_U0.grp_pooling_1_2_fu_98.mul_32s_30ns_62_1_1_U33"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_3_U0"},
	{"ID" : "22", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_3_U0.mul_31s_31s_32_1_1_U47"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.Block_entry_proc_3_U0.mul_32s_32s_32_1_1_U48"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.Block_entry_gmem_wr_proc_U0"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.conv_output_c_U"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.max_output_c_U"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.min_output_c_U"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.avg_output_c_U"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul_loc_channel_U"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.cmp3_loc_channel_U"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.mul10_loc_channel_U"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.cmp111_loc_channel_U"}]}
set DependenceCheckSize 0
