// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module process_images_entry_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        conv_output,
        conv_output_c_din,
        conv_output_c_full_n,
        conv_output_c_write,
        conv_output_c_num_data_valid,
        conv_output_c_fifo_cap,
        max_output,
        max_output_c_din,
        max_output_c_full_n,
        max_output_c_write,
        max_output_c_num_data_valid,
        max_output_c_fifo_cap,
        min_output,
        min_output_c_din,
        min_output_c_full_n,
        min_output_c_write,
        min_output_c_num_data_valid,
        min_output_c_fifo_cap,
        avg_output,
        avg_output_c_din,
        avg_output_c_full_n,
        avg_output_c_write,
        avg_output_c_num_data_valid,
        avg_output_c_fifo_cap
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [63:0] conv_output;
output  [63:0] conv_output_c_din;
input   conv_output_c_full_n;
output   conv_output_c_write;
input  [2:0] conv_output_c_num_data_valid;
input  [2:0] conv_output_c_fifo_cap;
input  [63:0] max_output;
output  [63:0] max_output_c_din;
input   max_output_c_full_n;
output   max_output_c_write;
input  [2:0] max_output_c_num_data_valid;
input  [2:0] max_output_c_fifo_cap;
input  [63:0] min_output;
output  [63:0] min_output_c_din;
input   min_output_c_full_n;
output   min_output_c_write;
input  [2:0] min_output_c_num_data_valid;
input  [2:0] min_output_c_fifo_cap;
input  [63:0] avg_output;
output  [63:0] avg_output_c_din;
input   avg_output_c_full_n;
output   avg_output_c_write;
input  [2:0] avg_output_c_num_data_valid;
input  [2:0] avg_output_c_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg conv_output_c_write;
reg max_output_c_write;
reg min_output_c_write;
reg avg_output_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    conv_output_c_blk_n;
reg    max_output_c_blk_n;
reg    min_output_c_blk_n;
reg    avg_output_c_blk_n;
reg    ap_block_state1;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        avg_output_c_blk_n = avg_output_c_full_n;
    end else begin
        avg_output_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        avg_output_c_write = 1'b1;
    end else begin
        avg_output_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        conv_output_c_blk_n = conv_output_c_full_n;
    end else begin
        conv_output_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        conv_output_c_write = 1'b1;
    end else begin
        conv_output_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        max_output_c_blk_n = max_output_c_full_n;
    end else begin
        max_output_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        max_output_c_write = 1'b1;
    end else begin
        max_output_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        min_output_c_blk_n = min_output_c_full_n;
    end else begin
        min_output_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        min_output_c_write = 1'b1;
    end else begin
        min_output_c_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (avg_output_c_full_n == 1'b0) | (min_output_c_full_n == 1'b0) | (max_output_c_full_n == 1'b0) | (conv_output_c_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign avg_output_c_din = avg_output;

assign conv_output_c_din = conv_output;

assign max_output_c_din = max_output;

assign min_output_c_din = min_output;

endmodule //process_images_entry_proc
