// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="full_pipeline_full_pipeline,hls_ip_2024_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=6568,HLS_SYN_LUT=8634,HLS_VERSION=2024_1}" *)

module full_pipeline (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 33'd1;
parameter    ap_ST_fsm_state2 = 33'd2;
parameter    ap_ST_fsm_state3 = 33'd4;
parameter    ap_ST_fsm_state4 = 33'd8;
parameter    ap_ST_fsm_state5 = 33'd16;
parameter    ap_ST_fsm_state6 = 33'd32;
parameter    ap_ST_fsm_state7 = 33'd64;
parameter    ap_ST_fsm_state8 = 33'd128;
parameter    ap_ST_fsm_state9 = 33'd256;
parameter    ap_ST_fsm_state10 = 33'd512;
parameter    ap_ST_fsm_state11 = 33'd1024;
parameter    ap_ST_fsm_state12 = 33'd2048;
parameter    ap_ST_fsm_state13 = 33'd4096;
parameter    ap_ST_fsm_state14 = 33'd8192;
parameter    ap_ST_fsm_state15 = 33'd16384;
parameter    ap_ST_fsm_state16 = 33'd32768;
parameter    ap_ST_fsm_state17 = 33'd65536;
parameter    ap_ST_fsm_state18 = 33'd131072;
parameter    ap_ST_fsm_state19 = 33'd262144;
parameter    ap_ST_fsm_state20 = 33'd524288;
parameter    ap_ST_fsm_state21 = 33'd1048576;
parameter    ap_ST_fsm_state22 = 33'd2097152;
parameter    ap_ST_fsm_state23 = 33'd4194304;
parameter    ap_ST_fsm_state24 = 33'd8388608;
parameter    ap_ST_fsm_state25 = 33'd16777216;
parameter    ap_ST_fsm_state26 = 33'd33554432;
parameter    ap_ST_fsm_state27 = 33'd67108864;
parameter    ap_ST_fsm_state28 = 33'd134217728;
parameter    ap_ST_fsm_state29 = 33'd268435456;
parameter    ap_ST_fsm_state30 = 33'd536870912;
parameter    ap_ST_fsm_state31 = 33'd1073741824;
parameter    ap_ST_fsm_state32 = 33'd2147483648;
parameter    ap_ST_fsm_state33 = 33'd4294967296;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 7;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [32:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] input_r;
wire   [31:0] height;
wire   [31:0] width;
wire   [63:0] kernel;
wire   [63:0] conv_out;
wire   [63:0] max_out;
wire   [63:0] min_out;
wire   [63:0] avg_out;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state3;
reg    gmem_blk_n_R;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
reg    gmem_blk_n_AW;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state26;
reg   [0:0] cmp38_i_reg_569;
reg   [63:0] avg_out_read_reg_517;
reg   [63:0] min_out_read_reg_522;
reg   [63:0] max_out_read_reg_527;
reg   [63:0] conv_out_read_reg_532;
reg   [31:0] width_read_reg_537;
reg   [31:0] height_read_reg_544;
reg   [63:0] input_r_read_reg_551;
wire   [31:0] sub_i_fu_250_p2;
reg   [31:0] sub_i_reg_559;
wire   [30:0] empty_fu_262_p1;
reg   [30:0] empty_reg_564;
wire   [0:0] cmp38_i_fu_266_p2;
wire   [63:0] wide_trip_count_i_fu_272_p1;
reg   [63:0] wide_trip_count_i_reg_573;
reg   [63:0] gmem_addr_reg_578;
wire   [44:0] add_ln5_2_fu_312_p2;
reg   [44:0] add_ln5_2_reg_587;
wire    ap_CS_fsm_state2;
wire   [30:0] add_ln5_1_fu_327_p2;
reg   [30:0] add_ln5_1_reg_595;
reg   [61:0] trunc_ln6_reg_600;
wire   [31:0] div_i_fu_397_p3;
reg   [31:0] div_i_reg_606;
wire   [31:0] div2_i_fu_450_p3;
reg   [31:0] div2_i_reg_611;
wire   [0:0] icmp_ln20_fu_458_p2;
reg   [0:0] icmp_ln20_reg_620;
wire   [0:0] icmp45_fu_464_p2;
reg   [0:0] icmp45_reg_624;
reg   [31:0] gmem_addr_read_reg_634;
reg   [31:0] gmem_addr_read_1_reg_639;
reg   [31:0] gmem_addr_read_2_reg_644;
reg   [31:0] gmem_addr_read_3_reg_649;
reg   [31:0] gmem_addr_read_4_reg_654;
reg   [31:0] gmem_addr_read_5_reg_659;
reg   [31:0] gmem_addr_read_6_reg_664;
reg   [31:0] gmem_addr_read_7_reg_669;
reg   [31:0] gmem_addr_read_8_reg_674;
wire    ap_CS_fsm_state27;
wire   [31:0] empty_52_fu_496_p3;
reg   [31:0] empty_52_reg_689;
wire    ap_CS_fsm_state28;
wire   [63:0] grp_fu_245_p2;
reg   [63:0] bound_reg_696;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_ap_start;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_ap_done;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_ap_idle;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_ap_ready;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWVALID;
wire   [63:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWADDR;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWID;
wire   [31:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWLEN;
wire   [2:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWSIZE;
wire   [1:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWBURST;
wire   [1:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWLOCK;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWCACHE;
wire   [2:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWPROT;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWQOS;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWREGION;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWUSER;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_WVALID;
wire   [31:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_WDATA;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_WSTRB;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_WLAST;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_WID;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_WUSER;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARVALID;
wire   [63:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARADDR;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARID;
wire   [31:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARLEN;
wire   [2:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARSIZE;
wire   [1:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARBURST;
wire   [1:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARLOCK;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARCACHE;
wire   [2:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARPROT;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARQOS;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARREGION;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARUSER;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_RREADY;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_BREADY;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_ap_start;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_ap_done;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_ap_idle;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_ap_ready;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWVALID;
wire   [63:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWADDR;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWID;
wire   [31:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWLEN;
wire   [2:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWSIZE;
wire   [1:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWBURST;
wire   [1:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWLOCK;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWCACHE;
wire   [2:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWPROT;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWQOS;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWREGION;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWUSER;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_WVALID;
wire   [31:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_WDATA;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_WSTRB;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_WLAST;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_WID;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_WUSER;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARVALID;
wire   [63:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARADDR;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARID;
wire   [31:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARLEN;
wire   [2:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARSIZE;
wire   [1:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARBURST;
wire   [1:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARLOCK;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARCACHE;
wire   [2:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARPROT;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARQOS;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARREGION;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARUSER;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_RREADY;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_BREADY;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_ap_start;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_ap_done;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_ap_idle;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_ap_ready;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWVALID;
wire   [63:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWADDR;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWID;
wire   [31:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWLEN;
wire   [2:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWSIZE;
wire   [1:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWBURST;
wire   [1:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWLOCK;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWCACHE;
wire   [2:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWPROT;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWQOS;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWREGION;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWUSER;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_WVALID;
wire   [31:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_WDATA;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_WSTRB;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_WLAST;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_WID;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_WUSER;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARVALID;
wire   [63:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARADDR;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARID;
wire   [31:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARLEN;
wire   [2:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARSIZE;
wire   [1:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARBURST;
wire   [1:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARLOCK;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARCACHE;
wire   [2:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARPROT;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARQOS;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARREGION;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARUSER;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_RREADY;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_BREADY;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_ap_start;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_ap_done;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_ap_idle;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_ap_ready;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWVALID;
wire   [63:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWADDR;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWID;
wire   [31:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWLEN;
wire   [2:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWSIZE;
wire   [1:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWBURST;
wire   [1:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWLOCK;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWCACHE;
wire   [2:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWPROT;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWQOS;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWREGION;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWUSER;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_WVALID;
wire   [31:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_WDATA;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_WSTRB;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_WLAST;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_WID;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_WUSER;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARVALID;
wire   [63:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARADDR;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARID;
wire   [31:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARLEN;
wire   [2:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARSIZE;
wire   [1:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARBURST;
wire   [1:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARLOCK;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARCACHE;
wire   [2:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARPROT;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARQOS;
wire   [3:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARREGION;
wire   [0:0] grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARUSER;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_RREADY;
wire    grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_BREADY;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg   [63:0] gmem_AWADDR;
reg   [31:0] gmem_AWLEN;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg   [31:0] gmem_WDATA;
reg   [3:0] gmem_WSTRB;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [63:0] gmem_ARADDR;
reg   [31:0] gmem_ARLEN;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire   [8:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    gmem_BREADY;
reg    grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_ap_start_reg;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
reg    grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_ap_start_reg;
wire    ap_CS_fsm_state29;
reg    grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_ap_start_reg;
reg   [32:0] ap_NS_fsm;
wire    ap_NS_fsm_state30;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state31;
reg    grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_ap_start_reg;
wire    ap_NS_fsm_state32;
wire    ap_CS_fsm_state32;
wire    ap_CS_fsm_state33;
wire  signed [63:0] p_cast_cast_fu_286_p1;
wire  signed [63:0] sext_ln6_fu_470_p1;
reg    ap_block_state3_io;
reg    ap_block_state26;
reg   [44:0] phi_mul_fu_118;
reg   [30:0] i_fu_122;
wire   [31:0] grp_fu_245_p0;
wire   [31:0] grp_fu_245_p1;
wire   [31:0] sub2_i_fu_256_p2;
wire   [61:0] p_cast_fu_276_p4;
wire   [31:0] zext_ln5_fu_318_p1;
wire   [63:0] zext_ln5_1_fu_333_p1;
wire   [63:0] add_ln5_fu_337_p2;
wire   [31:0] p_neg3_fu_359_p2;
wire   [30:0] p_lshr4_fu_364_p4;
wire   [31:0] p_lshr4_cast_fu_374_p1;
wire   [30:0] p_lshr_f6_fu_384_p4;
wire   [0:0] tmp_fu_352_p3;
wire   [31:0] p_neg_t5_fu_378_p2;
wire   [31:0] p_lshr_f6_cast_fu_393_p1;
wire   [31:0] p_neg_fu_412_p2;
wire   [30:0] p_lshr_fu_417_p4;
wire   [31:0] p_lshr_cast_fu_427_p1;
wire   [30:0] p_lshr_f_fu_437_p4;
wire   [0:0] tmp_38_fu_405_p3;
wire   [31:0] p_neg_t_fu_431_p2;
wire   [31:0] p_lshr_f_cast_fu_446_p1;
wire   [0:0] icmp_ln5_fu_322_p2;
reg    ap_block_state33_on_subcall_done;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
reg    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
reg    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
reg    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
reg    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
reg    ap_ST_fsm_state33_blk;
wire   [63:0] grp_fu_245_p00;
wire   [63:0] grp_fu_245_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 33'd1;
#0 grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_ap_start_reg = 1'b0;
#0 grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_ap_start_reg = 1'b0;
#0 grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_ap_start_reg = 1'b0;
#0 grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_ap_start_reg = 1'b0;
#0 phi_mul_fu_118 = 45'd0;
#0 i_fu_122 = 31'd0;
end

full_pipeline_full_pipeline_Pipeline_VITIS_LOOP_6_2 grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_ap_start),
    .ap_done(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_ap_done),
    .ap_idle(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_ap_idle),
    .ap_ready(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_ap_ready),
    .m_axi_gmem_AWVALID(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(gmem_AWREADY),
    .m_axi_gmem_AWADDR(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(gmem_WREADY),
    .m_axi_gmem_WDATA(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(gmem_BVALID),
    .m_axi_gmem_BREADY(grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .sub2_i(empty_reg_564),
    .sext_ln6(trunc_ln6_reg_600),
    .zext_ln5_2(phi_mul_fu_118),
    .input_r(input_r_read_reg_551),
    .gmem_addr_read_2(gmem_addr_read_2_reg_644),
    .gmem_addr_read_5(gmem_addr_read_5_reg_659),
    .gmem_addr_read_1(gmem_addr_read_1_reg_639),
    .gmem_addr_read_8(gmem_addr_read_8_reg_674),
    .gmem_addr_read(gmem_addr_read_reg_634),
    .gmem_addr_read_6(gmem_addr_read_6_reg_664),
    .gmem_addr_read_4(gmem_addr_read_4_reg_654),
    .gmem_addr_read_3(gmem_addr_read_3_reg_649),
    .gmem_addr_read_7(gmem_addr_read_7_reg_669)
);

full_pipeline_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2 grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_ap_start),
    .ap_done(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_ap_done),
    .ap_idle(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_ap_idle),
    .ap_ready(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_ap_ready),
    .m_axi_gmem_AWVALID(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(gmem_AWREADY),
    .m_axi_gmem_AWADDR(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(gmem_WREADY),
    .m_axi_gmem_WDATA(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(gmem_BVALID),
    .m_axi_gmem_BREADY(grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .div2_i(div2_i_reg_611),
    .bound(bound_reg_696),
    .input_r(input_r_read_reg_551),
    .zext_ln20(empty_52_reg_689),
    .max_out(max_out_read_reg_527)
);

full_pipeline_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2 grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_ap_start),
    .ap_done(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_ap_done),
    .ap_idle(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_ap_idle),
    .ap_ready(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_ap_ready),
    .m_axi_gmem_AWVALID(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(gmem_AWREADY),
    .m_axi_gmem_AWADDR(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(gmem_WREADY),
    .m_axi_gmem_WDATA(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(gmem_BVALID),
    .m_axi_gmem_BREADY(grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .div2_i(div2_i_reg_611),
    .bound(bound_reg_696),
    .input_r(input_r_read_reg_551),
    .zext_ln20(empty_52_reg_689),
    .min_out(min_out_read_reg_522)
);

full_pipeline_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2 grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_ap_start),
    .ap_done(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_ap_done),
    .ap_idle(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_ap_idle),
    .ap_ready(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_ap_ready),
    .m_axi_gmem_AWVALID(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(gmem_AWREADY),
    .m_axi_gmem_AWADDR(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(gmem_WREADY),
    .m_axi_gmem_WDATA(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(gmem_BVALID),
    .m_axi_gmem_BREADY(grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .div2_i(div2_i_reg_611),
    .bound(bound_reg_696),
    .input_r(input_r_read_reg_551),
    .zext_ln20(empty_52_reg_689),
    .avg_out(avg_out_read_reg_517)
);

full_pipeline_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .input_r(input_r),
    .height(height),
    .width(width),
    .kernel(kernel),
    .conv_out(conv_out),
    .max_out(max_out),
    .min_out(min_out),
    .avg_out(avg_out),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

full_pipeline_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_ARVALID),
    .I_CH0_ARREADY(gmem_ARREADY),
    .I_CH0_ARADDR(gmem_ARADDR),
    .I_CH0_ARLEN(gmem_ARLEN),
    .I_CH0_RVALID(gmem_RVALID),
    .I_CH0_RREADY(gmem_RREADY),
    .I_CH0_RDATA(gmem_RDATA),
    .I_CH0_RFIFONUM(gmem_RFIFONUM),
    .I_CH0_AWVALID(gmem_AWVALID),
    .I_CH0_AWREADY(gmem_AWREADY),
    .I_CH0_AWADDR(gmem_AWADDR),
    .I_CH0_AWLEN(gmem_AWLEN),
    .I_CH0_WVALID(gmem_WVALID),
    .I_CH0_WREADY(gmem_WREADY),
    .I_CH0_WDATA(gmem_WDATA),
    .I_CH0_WSTRB(gmem_WSTRB),
    .I_CH0_BVALID(gmem_BVALID),
    .I_CH0_BREADY(gmem_BREADY)
);

full_pipeline_mul_32ns_32ns_64_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_2_1_U35(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_245_p0),
    .din1(grp_fu_245_p1),
    .ce(1'b1),
    .dout(grp_fu_245_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state28)) begin
            grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_ap_start_reg <= 1'b1;
        end else if ((grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_ap_ready == 1'b1)) begin
            grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state30) & (1'b1 == ap_CS_fsm_state29))) begin
            grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_ap_start_reg <= 1'b1;
        end else if ((grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_ap_ready == 1'b1)) begin
            grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state32) & (1'b1 == ap_CS_fsm_state31))) begin
            grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_ap_start_reg <= 1'b1;
        end else if ((grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_ap_ready == 1'b1)) begin
            grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state20)) begin
            grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_ap_start_reg <= 1'b1;
        end else if ((grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_ap_ready == 1'b1)) begin
            grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_122 <= 31'd0;
    end else if (((1'b0 == ap_block_state26) & (1'b1 == ap_CS_fsm_state26))) begin
        i_fu_122 <= add_ln5_1_reg_595;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        phi_mul_fu_118 <= 45'd0;
    end else if (((1'b0 == ap_block_state26) & (1'b1 == ap_CS_fsm_state26))) begin
        phi_mul_fu_118 <= add_ln5_2_reg_587;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln5_1_reg_595 <= add_ln5_1_fu_327_p2;
        add_ln5_2_reg_587 <= add_ln5_2_fu_312_p2;
        div2_i_reg_611 <= div2_i_fu_450_p3;
        div_i_reg_606 <= div_i_fu_397_p3;
        icmp45_reg_624 <= icmp45_fu_464_p2;
        icmp_ln20_reg_620 <= icmp_ln20_fu_458_p2;
        trunc_ln6_reg_600 <= {{add_ln5_fu_337_p2[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        avg_out_read_reg_517 <= avg_out;
        cmp38_i_reg_569 <= cmp38_i_fu_266_p2;
        conv_out_read_reg_532 <= conv_out;
        empty_reg_564 <= empty_fu_262_p1;
        gmem_addr_reg_578 <= p_cast_cast_fu_286_p1;
        height_read_reg_544 <= height;
        input_r_read_reg_551 <= input_r;
        max_out_read_reg_527 <= max_out;
        min_out_read_reg_522 <= min_out;
        sub_i_reg_559 <= sub_i_fu_250_p2;
        wide_trip_count_i_reg_573[31 : 0] <= wide_trip_count_i_fu_272_p1[31 : 0];
        width_read_reg_537 <= width;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state28)) begin
        bound_reg_696 <= grp_fu_245_p2;
        empty_52_reg_689 <= empty_52_fu_496_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        gmem_addr_read_1_reg_639 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        gmem_addr_read_2_reg_644 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        gmem_addr_read_3_reg_649 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        gmem_addr_read_4_reg_654 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        gmem_addr_read_5_reg_659 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        gmem_addr_read_6_reg_664 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        gmem_addr_read_7_reg_669 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        gmem_addr_read_8_reg_674 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        gmem_addr_read_reg_634 <= gmem_RDATA;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((gmem_RVALID == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_RVALID == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_RVALID == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_RVALID == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_RVALID == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_RVALID == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_RVALID == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_RVALID == 1'b0)) begin
        ap_ST_fsm_state18_blk = 1'b1;
    end else begin
        ap_ST_fsm_state18_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_RVALID == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_ap_done == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state26)) begin
        ap_ST_fsm_state26_blk = 1'b1;
    end else begin
        ap_ST_fsm_state26_blk = 1'b0;
    end
end

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

always @ (*) begin
    if ((grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_ap_done == 1'b0)) begin
        ap_ST_fsm_state29_blk = 1'b1;
    end else begin
        ap_ST_fsm_state29_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

always @ (*) begin
    if ((grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_ap_done == 1'b0)) begin
        ap_ST_fsm_state31_blk = 1'b1;
    end else begin
        ap_ST_fsm_state31_blk = 1'b0;
    end
end

assign ap_ST_fsm_state32_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state33_on_subcall_done)) begin
        ap_ST_fsm_state33_blk = 1'b1;
    end else begin
        ap_ST_fsm_state33_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3_io)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_state33_on_subcall_done) & (1'b1 == ap_CS_fsm_state33))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state33_on_subcall_done) & (1'b1 == ap_CS_fsm_state33))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3))) begin
        gmem_ARADDR = gmem_addr_reg_578;
    end else if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32))) begin
        gmem_ARADDR = grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30))) begin
        gmem_ARADDR = grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28))) begin
        gmem_ARADDR = grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_ARADDR = grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARADDR;
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3))) begin
        gmem_ARLEN = 64'd9;
    end else if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32))) begin
        gmem_ARLEN = grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30))) begin
        gmem_ARLEN = grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28))) begin
        gmem_ARLEN = grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_ARLEN = grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARLEN;
    end else begin
        gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3))) begin
        gmem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32))) begin
        gmem_ARVALID = grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30))) begin
        gmem_ARVALID = grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28))) begin
        gmem_ARVALID = grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_ARVALID = grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3))) begin
        gmem_AWADDR = sext_ln6_fu_470_p1;
    end else if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32))) begin
        gmem_AWADDR = grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWADDR;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30))) begin
        gmem_AWADDR = grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWADDR;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28))) begin
        gmem_AWADDR = grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWADDR;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_AWADDR = grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWADDR;
    end else begin
        gmem_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3))) begin
        gmem_AWLEN = wide_trip_count_i_reg_573;
    end else if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32))) begin
        gmem_AWLEN = grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWLEN;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30))) begin
        gmem_AWLEN = grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWLEN;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28))) begin
        gmem_AWLEN = grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWLEN;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_AWLEN = grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWLEN;
    end else begin
        gmem_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3))) begin
        gmem_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32))) begin
        gmem_AWVALID = grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_AWVALID;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30))) begin
        gmem_AWVALID = grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_AWVALID;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28))) begin
        gmem_AWVALID = grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_AWVALID;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_AWVALID = grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_AWVALID;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state26) & (1'b1 == ap_CS_fsm_state26) & (cmp38_i_reg_569 == 1'd1))) begin
        gmem_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32))) begin
        gmem_BREADY = grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_BREADY;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30))) begin
        gmem_BREADY = grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_BREADY;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28))) begin
        gmem_BREADY = grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_BREADY;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_BREADY = grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_BREADY;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19)) | ((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state18)) | ((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state17)) | ((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state16)) | ((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15)) | ((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state14)) | ((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13)) | ((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11)))) begin
        gmem_RREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32))) begin
        gmem_RREADY = grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30))) begin
        gmem_RREADY = grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28))) begin
        gmem_RREADY = grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_RREADY = grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32))) begin
        gmem_WDATA = grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_WDATA;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30))) begin
        gmem_WDATA = grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_WDATA;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28))) begin
        gmem_WDATA = grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_WDATA;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_WDATA = grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_WDATA;
    end else begin
        gmem_WDATA = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32))) begin
        gmem_WSTRB = grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_WSTRB;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30))) begin
        gmem_WSTRB = grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_WSTRB;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28))) begin
        gmem_WSTRB = grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_WSTRB;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_WSTRB = grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_WSTRB;
    end else begin
        gmem_WSTRB = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32))) begin
        gmem_WVALID = grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_m_axi_gmem_WVALID;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state30))) begin
        gmem_WVALID = grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_m_axi_gmem_WVALID;
    end else if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28))) begin
        gmem_WVALID = grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_m_axi_gmem_WVALID;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_WVALID = grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_m_axi_gmem_WVALID;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) & (cmp38_i_reg_569 == 1'd1))) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln5_fu_322_p2 == 1'd0) & (icmp_ln20_fu_458_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else if (((icmp_ln5_fu_322_p2 == 1'd0) & (icmp_ln20_fu_458_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state27;
            end else if (((icmp_ln5_fu_322_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (cmp38_i_reg_569 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_io) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        ap_ST_fsm_state14 : begin
            if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state15))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        ap_ST_fsm_state17 : begin
            if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if (((grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            if (((1'b0 == ap_block_state26) & (1'b1 == ap_CS_fsm_state26))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            if (((grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state29))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state29;
            end
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            if (((grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state31))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            if (((1'b0 == ap_block_state33_on_subcall_done) & (1'b1 == ap_CS_fsm_state33))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln5_1_fu_327_p2 = (i_fu_122 + 31'd1);

assign add_ln5_2_fu_312_p2 = (phi_mul_fu_118 + 45'd8528);

assign add_ln5_fu_337_p2 = (zext_ln5_1_fu_333_p1 + conv_out_read_reg_532);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_NS_fsm_state30 = ap_NS_fsm[32'd29];

assign ap_NS_fsm_state32 = ap_NS_fsm[32'd31];

always @ (*) begin
    ap_block_state26 = ((gmem_BVALID == 1'b0) & (cmp38_i_reg_569 == 1'd1));
end

always @ (*) begin
    ap_block_state33_on_subcall_done = ((grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_ap_done == 1'b0) & (icmp_ln20_reg_620 == 1'd1));
end

always @ (*) begin
    ap_block_state3_io = ((gmem_ARREADY == 1'b0) | (gmem_AWREADY == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cmp38_i_fu_266_p2 = (($signed(sub2_i_fu_256_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign div2_i_fu_450_p3 = ((tmp_38_fu_405_p3[0:0] == 1'b1) ? p_neg_t_fu_431_p2 : p_lshr_f_cast_fu_446_p1);

assign div_i_fu_397_p3 = ((tmp_fu_352_p3[0:0] == 1'b1) ? p_neg_t5_fu_378_p2 : p_lshr_f6_cast_fu_393_p1);

assign empty_52_fu_496_p3 = ((icmp45_reg_624[0:0] == 1'b1) ? div2_i_reg_611 : 32'd0);

assign empty_fu_262_p1 = sub2_i_fu_256_p2[30:0];

assign grp_fu_245_p0 = grp_fu_245_p00;

assign grp_fu_245_p00 = div_i_reg_606;

assign grp_fu_245_p1 = grp_fu_245_p10;

assign grp_fu_245_p10 = div2_i_reg_611;

assign grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_ap_start = grp_full_pipeline_Pipeline_VITIS_LOOP_20_1_VITIS_LOOP_21_2_fu_212_ap_start_reg;

assign grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_ap_start = grp_full_pipeline_Pipeline_VITIS_LOOP_36_1_VITIS_LOOP_37_2_fu_223_ap_start_reg;

assign grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_ap_start = grp_full_pipeline_Pipeline_VITIS_LOOP_52_1_VITIS_LOOP_53_2_fu_234_ap_start_reg;

assign grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_ap_start = grp_full_pipeline_Pipeline_VITIS_LOOP_6_2_fu_193_ap_start_reg;

assign icmp45_fu_464_p2 = (($signed(p_lshr_f_fu_437_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln20_fu_458_p2 = (($signed(p_lshr_f6_fu_384_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln5_fu_322_p2 = (($signed(zext_ln5_fu_318_p1) < $signed(sub_i_reg_559)) ? 1'b1 : 1'b0);

assign p_cast_cast_fu_286_p1 = $signed(p_cast_fu_276_p4);

assign p_cast_fu_276_p4 = {{kernel[63:2]}};

assign p_lshr4_cast_fu_374_p1 = p_lshr4_fu_364_p4;

assign p_lshr4_fu_364_p4 = {{p_neg3_fu_359_p2[31:1]}};

assign p_lshr_cast_fu_427_p1 = p_lshr_fu_417_p4;

assign p_lshr_f6_cast_fu_393_p1 = p_lshr_f6_fu_384_p4;

assign p_lshr_f6_fu_384_p4 = {{height_read_reg_544[31:1]}};

assign p_lshr_f_cast_fu_446_p1 = p_lshr_f_fu_437_p4;

assign p_lshr_f_fu_437_p4 = {{width_read_reg_537[31:1]}};

assign p_lshr_fu_417_p4 = {{p_neg_fu_412_p2[31:1]}};

assign p_neg3_fu_359_p2 = (32'd0 - height_read_reg_544);

assign p_neg_fu_412_p2 = (32'd0 - width_read_reg_537);

assign p_neg_t5_fu_378_p2 = (32'd0 - p_lshr4_cast_fu_374_p1);

assign p_neg_t_fu_431_p2 = (32'd0 - p_lshr_cast_fu_427_p1);

assign sext_ln6_fu_470_p1 = $signed(trunc_ln6_reg_600);

assign sub2_i_fu_256_p2 = ($signed(width) + $signed(32'd4294967294));

assign sub_i_fu_250_p2 = ($signed(height) + $signed(32'd4294967294));

assign tmp_38_fu_405_p3 = width_read_reg_537[32'd31];

assign tmp_fu_352_p3 = height_read_reg_544[32'd31];

assign wide_trip_count_i_fu_272_p1 = sub2_i_fu_256_p2;

assign zext_ln5_1_fu_333_p1 = phi_mul_fu_118;

assign zext_ln5_fu_318_p1 = i_fu_122;

always @ (posedge ap_clk) begin
    wide_trip_count_i_reg_573[63:32] <= 32'b00000000000000000000000000000000;
end

endmodule //full_pipeline
